### ISSUE TITLE
Unable to emerge Hyprland 

### ISSUE THREAD

**Issue by Devarth123** [x0rzavi/x0rzavi-overlay#1]
```~ ❯ doas emerge hyprland --verbose --autounmask-continue
doas (ew@ganchoo) password: 
!!! INVALID ACCEPT_KEYWORDS: ~x86_64
 * WARNING: The FEATURES variable contains one or more values that
 * should be disabled under normal circumstances: keepwork

 * IMPORTANT: 14 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.


These are the packages that would be merged, in order:

Calculating dependencies  !!! Invalid db entry: /var/db/pkg/gui-wm/hyprland                                        ... done!

!!! All ebuilds that could satisfy "hyprland" have been masked.
!!! One of the following masked packages is required to complete your request:
- gui-wm/hyprland-9999::x0rzavi (masked by: missing keyword)

For more information, see the MASKED PACKAGES section in the emerge
man page or refer to the Gentoo Handbook.
```

make.conf keyword 
```
ACCEPT_LICENSE="-* @FREE BSD-3"
ACCEPT_KEYWORDS="~amd64 ~x86_64"
```

**Comment by x0rzavi** [comment]
Firstly there's no such keyword named `x86_64`, for amd64 architectures its just `amd64`. Secondly you can accept keywords selectively for packages following this https://wiki.gentoo.org/wiki//etc/portage/package.accept_keywords

**Comment by Devarth123** [comment]
Still doesnt work :pain: 

## package.accept_keywords
```gui-wm/hyprland ~amd64```

**Comment by x0rzavi** [comment]
please post full log

**Comment by Devarth123** [comment]
How can there be log if i wasn't able to emerge it?
Anyways i compiled it directly by hunting deps

**Comment by x0rzavi** [comment]
I mean, just whatever the your terminal shows 🙂 If everything is alright with portage, it should just show something related to dependency resolution at best.

**Comment by Devarth123** [comment]
```~ ❯ doas emerge -a --verbose hyprland
doas (ew@ganchoo) password: 
 * WARNING: The FEATURES variable contains one or more values that
 * should be disabled under normal circumstances: keepwork

 * IMPORTANT: 14 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.

These are the packages that would be merged, in order:

Calculating dependencies... done!

!!! All ebuilds that could satisfy "hyprland" have been masked.
!!! One of the following masked packages is required to complete your request:
- gui-wm/hyprland-9999::x0rzavi (masked by: missing keyword)

For more information, see the MASKED PACKAGES section in the emerge
man page or refer to the Gentoo Handbook.
``` 
here is everything my terminal shows, btw does this ebuild work for you?

**Comment by x0rzavi** [comment]
> masked by: missing keyword

9999 packages must be unmasked manually https://wiki.gentoo.org/wiki/Knowledge_Base:Accepting_a_keyword_for_a_single_package#Additional_notes

> does this ebuild work for you?

why would post post it publicly if it doesn't? I accept the fact that there maybe some issues with dependency resolution, but the logs clearly shows that the issue isn't with my ebuild. 🤷🏻 Report back if building fails.

**Comment by Devarth123** [comment]
Seems work,  thanks!
